## **Pandas Exercise set**

## **Exercise 01**

### 01. Import pandas and load dataset

In [1]:
import numpy as np
import pandas as pd

np.set_printoptions(suppress=True)
pd.set_option('display.float_format', '{:.2f}'.format)

In [2]:
df = pd.read_csv("exercises2_datafiles/loans.csv")

# prining the head of the data 
df.head

<bound method NDFrame.head of                                     Loan ID  Loan Status  Current Loan Amount  \
0      14dd8831-6af5-400b-83ec-68e61888a048   Fully Paid            445412.00
1      4eed4e6a-aa2f-4c91-8651-ce984ee8fb26   Fully Paid          99999999.00
2      77598f7b-32e7-4e3b-a6e5-06ba0d98fe8a   Fully Paid            347666.00
3      89d8cb0c-e5c2-4f54-b056-48a645c543dd  Charged Off            206602.00
4      273581de-85d8-4332-81a5-19b04ce68666   Fully Paid            217646.00
...                                     ...          ...                  ...
70316  8506a4e9-af7d-47d2-a1bf-7ea2c41858f0   Fully Paid            210584.00
70317  06eba04f-58fc-424a-b666-ed72aa008900   Fully Paid          99999999.00
70318  e1cb4050-eff5-4bdb-a1b0-aabd3f7eaac7   Fully Paid            103136.00
70319  81ab928b-d1a5-4523-9a3c-271ebb01b4fb   Fully Paid            530332.00
70320  c63916c6-6d46-47a9-949a-51d09af4414f   Fully Paid          99999999.00

             Term  Credit Score  Annual Income Home Ownership  \
0      Short Term        709.00     1167493.00  Home Mortgage
1      Short Term        741.00     2231892.00       Own Home
2       Long Term        721.00      806949.00       Own Home
3      Short Term       7290.00      896857.00  Home Mortgage
4      Short Term        730.00     1184194.00  Home Mortgage
...           ...           ...            ...            ...
70316  Short Term        719.00      783389.00  Home Mortgage
70317  Short Term        732.00     1289416.00           Rent
70318  Short Term        742.00     1150545.00           Rent
70319  Short Term        746.00     1717524.00           Rent
70320  Short Term        743.00      935180.00       Own Home

                  Purpose  Monthly Debt  Years of Credit History  \
0       Home Improvements       5214.74                    17.20
1      Debt Consolidation      29200.53                    14.90
2      Debt Consolidation       8741.90                    12.00
3      Debt Consolidation      16367.74                    17.30
4      Debt Consolidation      10855.08                    19.60
...                   ...           ...                      ...
70316               Other       3727.61                    17.40
70317  Debt Consolidation      13109.05                     9.40
70318  Debt Consolidation       7315.57                    18.80
70319  Debt Consolidation       9890.07                    15.00
70320  Debt Consolidation       9118.10                    13.00

       Number of Open Accounts  Number of Credit Problems  \
0                         6.00                       1.00
1                        18.00                       1.00
2                         9.00                       0.00
3                         6.00                       0.00
4                        13.00                       1.00
...                        ...                        ...
70316                     6.00                       0.00
70317                    22.00                       0.00
70318                    12.00                       1.00
70319                     8.00                       0.00
70320                     4.00                       1.00

       Current Credit Balance  Maximum Open Credit  Bankruptcies
0                   228190.00            416746.00          1.00
1                   297996.00            750090.00          0.00
2                   256329.00            386958.00          0.00
3                   215308.00            272448.00          0.00
4                   122170.00            272052.00          1.00
...                       ...                  ...           ...
70316                  456.00            259160.00          0.00
70317               153045.00            509234.00          0.00
70318               109554.00            537548.00          1.00
70319               404225.00            738254.00          0.00
70320                45600.00             91014.00          1.00

[70321 rows x 15 columns]>

### 02. remove unrealistically large loans

In [3]:
df = df[df["Current Loan Amount"] < 99999999]

df.head

<bound method NDFrame.head of                                     Loan ID  Loan Status  Current Loan Amount  \
0      14dd8831-6af5-400b-83ec-68e61888a048   Fully Paid            445412.00
2      77598f7b-32e7-4e3b-a6e5-06ba0d98fe8a   Fully Paid            347666.00
3      89d8cb0c-e5c2-4f54-b056-48a645c543dd  Charged Off            206602.00
4      273581de-85d8-4332-81a5-19b04ce68666   Fully Paid            217646.00
5      8af915d9-9e91-44a0-b5a2-564a45c12089   Fully Paid            548746.00
...                                     ...          ...                  ...
70313  3b2a09bb-3467-4d2f-bd8f-260fdc5760be   Fully Paid            179454.00
70314  38530a21-5a57-47f5-9aaa-b4475b1db345   Fully Paid            781022.00
70316  8506a4e9-af7d-47d2-a1bf-7ea2c41858f0   Fully Paid            210584.00
70318  e1cb4050-eff5-4bdb-a1b0-aabd3f7eaac7   Fully Paid            103136.00
70319  81ab928b-d1a5-4523-9a3c-271ebb01b4fb   Fully Paid            530332.00

             Term  Credit Score  Annual Income Home Ownership  \
0      Short Term        709.00     1167493.00  Home Mortgage
2       Long Term        721.00      806949.00       Own Home
3      Short Term       7290.00      896857.00  Home Mortgage
4      Short Term        730.00     1184194.00  Home Mortgage
5      Short Term        678.00     2559110.00           Rent
...           ...           ...            ...            ...
70313  Short Term        708.00     1356068.00  Home Mortgage
70314  Short Term        741.00     2582404.00  Home Mortgage
70316  Short Term        719.00      783389.00  Home Mortgage
70318  Short Term        742.00     1150545.00           Rent
70319  Short Term        746.00     1717524.00           Rent

                  Purpose  Monthly Debt  Years of Credit History  \
0       Home Improvements       5214.74                    17.20
2      Debt Consolidation       8741.90                    12.00
3      Debt Consolidation      16367.74                    17.30
4      Debt Consolidation      10855.08                    19.60
5      Debt Consolidation      18660.28                    22.60
...                   ...           ...                      ...
70313  Debt Consolidation      22318.54                    22.70
70314  Debt Consolidation      51648.08                    26.30
70316               Other       3727.61                    17.40
70318  Debt Consolidation       7315.57                    18.80
70319  Debt Consolidation       9890.07                    15.00

       Number of Open Accounts  Number of Credit Problems  \
0                         6.00                       1.00
2                         9.00                       0.00
3                         6.00                       0.00
4                        13.00                       1.00
5                         4.00                       0.00
...                        ...                        ...
70313                    25.00                       0.00
70314                    25.00                       0.00
70316                     6.00                       0.00
70318                    12.00                       1.00
70319                     8.00                       0.00

       Current Credit Balance  Maximum Open Credit  Bankruptcies
0                   228190.00            416746.00          1.00
2                   256329.00            386958.00          0.00
3                   215308.00            272448.00          0.00
4                   122170.00            272052.00          1.00
5                   437171.00            555038.00          0.00
...                       ...                  ...           ...
70313               387410.00           1705616.00          0.00
70314               669180.00           2299198.00          0.00
70316                  456.00            259160.00          0.00
70318               109554.00            537548.00          1.00
70319               404225.00            738254.00          0.00

[58893 rows x 15 columns]>

### 03. loans that have highest credit balance

In [4]:
df.nlargest(5, "Current Loan Amount")

,Loan ID,Loan Status,Current Loan Amount,Term,Credit Score,Annual Income,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies
16422,4fed402f-4298-4f5c-8d30-05b1f1819c00,Fully Paid,789250.00,Long Term,672.00,1752750.00,Rent,Debt Consolidation,29212.50,8.50,11.00,0.00,971508.00,1538856.00,0.00
32147,b7923e12-395b-49d6-97ee-ca0ed25b65c2,Fully Paid,789250.00,Short Term,721.00,8054480.00,Home Mortgage,Debt Consolidation,114105.07,31.40,21.00,0.00,1826147.00,2405568.00,0.00
35079,a572e23e-fc67-4d7a-92d0-3cad85ec0a47,Fully Paid,789184.00,Long Term,685.00,4381457.00,Home Mortgage,Debt Consolidation,46370.26,17.80,17.00,0.00,694089.00,1096414.00,0.00
36039,f95fe414-2e62-4d41-82be-e162e5715fef,Fully Paid,789184.00,Long Term,713.00,2239416.00,Home Mortgage,Debt Consolidation,44228.20,17.30,17.00,0.00,632263.00,1247180.00,0.00
36417,8d59aa00-d111-4439-9b32-82cc5ab5b940,Fully Paid,789184.00,Long Term,716.00,1596798.00,Home Mortgage,Debt Consolidation,44710.23,28.50,15.00,0.00,921139.00,1760044.00,0.00

### 04. Loans with smallest annual income

In [5]:
df.nsmallest(5, "Annual Income")

,Loan ID,Loan Status,Current Loan Amount,Term,Credit Score,Annual Income,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies
48729,fdda52f3-bbfa-45da-80b5-2bd9b68638ed,Charged Off,30448.00,Short Term,736.00,76627.00,Rent,Debt Consolidation,845.50,9.50,8.00,0.00,28177.00,147598.00,0.00
38169,9ed28b3a-c3a9-4ae4-93e6-3de7ff42f64e,Fully Paid,61490.00,Short Term,662.00,81092.00,Rent,Educational Expenses,0.00,11.00,6.00,0.00,0.00,0.00,0.00
7624,241e16a3-c198-4d8e-8dad-c927fd7c7d24,Fully Paid,34342.00,Short Term,715.00,111245.00,Own Home,Other,463.60,29.70,3.00,0.00,6840.00,264044.00,0.00
18719,1596dd1e-d8ba-45eb-b4a8-ee75736b66b6,Fully Paid,47894.00,Short Term,688.00,130150.00,Own Home,Other,2971.41,21.30,3.00,0.00,100510.00,191730.00,0.00
22489,c28d26b0-a805-4e71-b389-f9fc1c9d8bb2,Fully Paid,46860.00,Short Term,714.00,134881.00,Rent,Debt Consolidation,1641.22,6.00,4.00,0.00,43491.00,89298.00,0.00

### 05. Min, max, mean and quantiles (25%, 50%, 75%)

In [6]:
df["Current Loan Amount"].describe()

count    58893.00
mean    312122.30
std     185174.86
min      15422.00
25%     172876.00
50%     267454.00
75%     432432.00
max     789250.00
Name: Current Loan Amount, dtype: float64

In [7]:
print('Min:  ', df['Current Loan Amount'].min())
print('Max:  ', df['Current Loan Amount'].max())
print('Mean: ', df['Current Loan Amount'].mean())
print('25%:  ', df['Current Loan Amount'].quantile(0.25))
print('50%:  ', df['Current Loan Amount'].quantile(0.50))
print('75%:  ', df['Current Loan Amount'].quantile(0.75))

Min:   15422.0
Max:   789250.0
Mean:  312122.29711510707
25%:   172876.0
50%:   267454.0
75%:   432432.0

### 6. Create a new field: Actual Annual Income

In [8]:
df["Actual Annual Income"] = df["Annual Income"] - (12 * df["Monthly Debt"])

df[["Annual Income", "Monthly Debt", "Actual Annual Income"]].head(10)

    Annual Income  Monthly Debt  Actual Annual Income
0      1167493.00       5214.74            1104916.12
2       806949.00       8741.90             702046.20
3       896857.00      16367.74             700444.12
4      1184194.00      10855.08            1053933.04
5      2559110.00      18660.28            2335186.64
6      1454735.00      39277.75             983402.00
10      693234.00      14211.24             522699.12
11     1821967.00      17612.24            1610620.12
12     1791738.00       2478.55            1761995.40
13     1133274.00       9632.81            1017680.28

### 07. Long term loans quantity

In [9]:
count = df["Term"].value_counts()
print(count)
print(f"Number of long term loans : {count.get("Long Term")}")

Term
Short Term    42141
Long Term     16752
Name: count, dtype: int64
Number of long term loans : 16752

### 08. 3 most common loan purposes

In [10]:
# replace the "other" with "Other" 
df["Purpose"] = df["Purpose"].replace("other", "Other")

# get all purposes 
purpose_count = df["Purpose"].value_counts()
print(purpose_count)

# top 3 most common purposes
print(f"\n {purpose_count.head(3)}")

Purpose
Debt Consolidation      46474
Other                    5437
Home Improvements        3397
Business Loan             946
Buy a Car                 743
Medical Bills             645
Buy House                 396
major_purchase            215
Take a Trip               203
small_business            175
moving                     90
wedding                    57
Educational Expenses       55
vacation                   54
renewable_energy            6
Name: count, dtype: int64

 Purpose
Debt Consolidation    46474
Other                  5437
Home Improvements      3397
Name: count, dtype: int64

### Extra task: Distribution of Number of Credit Problems

In [11]:
credit_problems = df["Number of Credit Problems"].value_counts()
print(credit_problems)

Number of Credit Problems
0.00    50788
1.00     7014
2.00      753
3.00      216
4.00       72
5.00       33
6.00       10
7.00        5
8.00        2
Name: count, dtype: int64

In [12]:
# Findings:
# The majority of borrowers have 0 credit problems.
# Very few borrowers have 2 or more problems. This means that most customers have clean credit histories.

### 09. Unique Home Ownership options

In [13]:
unique_values = df["Home Ownership"].unique()
print(unique_values)

<StringArray>
['Home Mortgage', 'Own Home', 'Rent']
Length: 3, dtype: str

### Extra task: How many loaners have more than 1 bankruptcy

In [14]:
bankruptcy = df[df["Bankruptcies"] > 1]
print(f"loaners have more than 1 bankruptcy : {len(bankruptcy)}")

loaners have more than 1 bankruptcy : 305

### Extra task: How many Short Term loans are for Home Improvements?

In [15]:
# filter short term loans 
short_term = df[df['Term'] == 'Short Term']

# short term loan purposes
short_term_purposes = short_term["Purpose"].value_counts()
print(short_term_purposes)

# home improvement purpose
home_improvement_count = short_term_purposes.get('Home Improvements')
print(f"\nShort term loans for home improvements: {home_improvement_count}")

Purpose
Debt Consolidation      32803
Other                    4302
Home Improvements        2324
Business Loan             668
Buy a Car                 571
Medical Bills             524
Buy House                 274
Take a Trip               176
major_purchase            153
small_business            120
moving                     74
vacation                   51
Educational Expenses       49
wedding                    47
renewable_energy            5
Name: count, dtype: int64

Short term loans for home improvements: 2324

### Extra task: Correlation Analysis

In [16]:
# Option A: Annual Income vs Number of Open Accounts ---
corr_a = df['Annual Income'].corr(df['Number of Open Accounts'])
print(f'Correlation (Annual Income vs Number of Open Accounts): {corr_a:.4f}')

Correlation (Annual Income vs Number of Open Accounts): 0.1376

**Annual Income vs Number of Open Accounts:** A weak correlation suggests that having more open accounts does not strongly correlate with higher or lower income.

In [17]:
# Option B: Number of Credit Problems vs Bankruptcies ---
corr_b = df['Number of Credit Problems'].corr(df['Bankruptcies'])
print(f'Correlation (Number of Credit Problems vs Bankruptcies): {corr_b:.4f}')

Correlation (Number of Credit Problems vs Bankruptcies): 0.7630

**Number of Credit Problems vs Bankruptcies:** this correlation would confirm that borrowers with more credit problems also tend to have more bankruptcies. This is true because bankruptcies are one of the most severe forms of credit problems.